### ISSUE TITLE
README: Write down how to create own decorators

### ISSUE THREAD

**Issue by Calamari** [Calamari/BehaviorTree.js#14]

**Comment by Calamari** [comment]
Hi. Thanks.

The issues I put up here, are mainly for the rewrite (which is basically finished, and just needs proper testing) that is found in the 2.0 branch. This is also uses ES7 syntax, which makes things more readable. So writing Decorators there is a bit different to the 1.0 version.

Anyhow, to make an event based BT you need to call the BT run method multiple times a second (although I don't recommend to call it as often as on every frame) and attach a blackboard to it (which also could be the agent it handles) so the Decorators can check on the blackboard if a condition is happening. That is the closest way to get a BT to be "event-driven", as far as I know. The examples of BTs of Unreal engine I saw do look similar to what I described.

I am currently on vacation this week, so I am not often responding, but if you still have question, please ask. I like to help :)
What are you building @soundyogi?

**Comment by soundyogi** [comment]
Nice Description! 
Thanks I will hack around a bit as soon as I get some air.

Why, Well the ue4 BT implementation is just very good and my team got used to it.
(I think event-driven behavior trees are the most advanced concept at the time, also excessive use of decorators is encouraged and your lib is the first I like in that regard.
But unreal engine fucks up our velocity thats why I have to transition to js. (4h for packaging? nu-uh)
Games mainly, but since BTs are so flexible, I cant think of anything you could not do with them.
I actually think they would fit well in traditional apps aswell. DAG for the win.

I like the 2.0 rewrite. Very Clean. I will have to get some more reading done!
Until Then!

**Comment by finscn** [comment]
ES7 is too  radical , I think ES6 is good enough in next two years.

**Comment by soundyogi** [comment]
Well the damage is already done :D
And I think es7 is a good choice.

**Comment by Calamari** [comment]
So, the damage is definitely done. The v2 is out now. 

Since this is a ticket related to this version creation I'll close it. If you like, @soundyogi play around with it. Decorator creation should be relatively straight forward. If something is not working as expected or have another ideas, please reach out or create an issue. :)

**Comment by soundyogi** [comment]
Perfect Timing Man I am going to check it out and report back :) :+1:
